

  <match **>
      @type rewrite_tag_filter
      <rule>
        key message
        pattern /error|exception|timeout/i
        tag error.${tag}
      </rule>
      <rule>
        key message
        pattern /.*/
        tag normal.${tag}
      </rule>
    </match>

    ########################################################
    # 4. 对匹配 error.** 的日志计数，生成 Prometheus 指标
    ########################################################
    <filter error.**>
      @type prometheus
      <metric>
        name fluentd_error_logs_total
        type counter
        desc "Number of error logs detected by Fluentd"
      </metric>
      <labels>
        namespace ${record["kubernetes"]["namespace_name"]}
        pod ${record["kubernetes"]["pod_name"]}
        container ${record["kubernetes"]["container_name"]}
      </labels>
    </filter>
    <match **>
      @type stdout
    </match>
   
   <source>
      @type tail
      @id in_tail_container_logs
      path /var/log/containers/*.log
      pos_file /fluentd/etc/pos/container.log.pos
      tag kube.*
      read_from_head true
      refresh_interval 5
      multiline_flush_interval 5
      <parse>
        @type json
        time_key time
        time_format %Y-%m-%dT%H:%M:%S.%NZ
        keep_time_key true
        emit_invalid_record_to_error true
      </parse>
    </source>
    
    <filter kube.**>
      @type kubernetes_metadata
      @id filter_kube_metadata
      kubernetes_url https://kubernetes.default.svc
      verify_ssl false
      ca_file /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      bearer_token_file /var/run/secrets/kubernetes.io/serviceaccount/token
      merge_json_log true
      labels true
      annotations true
    </filter>
apiVersion: fluentd.fluent.io/v1alpha1
kind: ClusterInput
metadata:
  name: container-logs
  labels:
    app: fluentd-agent
spec:
  tail:
    path: /var/log/containers/*.log
    tag: kube.*
    readFromHead: true
    posFile: /fluentd/etc/pos/container.log.pos
    parser:
      type: json
      timeKey: time
      timeFormat: "%Y-%m-%dT%H:%M:%S.%NZ"
      timeType: string
      emitInvalidRecordToError: true
---
apiVersion: fluentd.fluent.io/v1alpha1
kind: ClusterFilter
metadata:
  name: add-k8s-meta
  labels:
    app: fluentd-agent
spec:
  match: kube.*
  filters:
    - kubernetes_metadata:
        kube_url: https://kubernetes.default.svc
        cache_size: 1000
        cache_ttl: 3600
        watch: true
        verify_ssl: false
        use_journal: false
        merge_json_log: true
        labels: true
        annotations: true

apiVersion: fluentd.fluent.io/v1alpha1
kind: Fluentd
metadata:
  name: fluentd-agent
  namespace: logging
spec:
  mode: Agent
  image: fluent/fluentd:v1.16-debian-1.0

  fluentdCfgSelector:
    matchLabels:
      app: fluentd-agent

  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi

  volumes:
    - name: varlog
      hostPath:
        path: /var/log
    - name: dockercontainers
      hostPath:
        path: /var/lib/docker/containers

  volumeMounts:
    - name: varlog
      mountPath: /var/log
    - name: dockercontainers
      mountPath: /var/lib/docker/containers
      readOnly: true
---
apiVersion: fluentd.fluent.io/v1alpha1
kind: Fluentd
metadata:
  name: fluentd-aggregator
  namespace: logging
spec:
  mode: Aggregator
  image: fluent/fluentd:v1.16-debian-1.0
  replicas: 1

  fluentdCfgSelector:
    matchLabels:
      app: fluentd-aggregator

  service:
    type: ClusterIP
    ports:
      - name: forward
        port: 24224
        targetPort: 24224

  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi

---
# Agent 收集容器日志
apiVersion: fluentd.fluent.io/v1alpha1
kind: ClusterInput
metadata:
  name: container-logs
  namespace: logging
spec:
  tail:
    path: /var/log/containers/*.log
    tag: kube.*
    readFromHead: true
---
# Agent 输出转发给 Aggregator
apiVersion: fluentd.fluent.io/v1alpha1
kind: ClusterOutput
metadata:
  name: forward-to-aggregator
  namespace: logging
spec:
  match: kube.*
  forward:
    servers:
      - host: fluentd-aggregator.logging.svc
        port: 24224
---
# Aggregator 接收 Agent 转发日志
apiVersion: fluentd.fluent.io/v1alpha1
kind: ClusterInput
metadata:
  name: forward-input
  namespace: logging
spec:
  forward:
    port: 24224
---
# Aggregator 输出到 stdout（可改为 Elasticsearch/Loki）
apiVersion: fluentd.fluent.io/v1alpha1
kind: ClusterOutput
metadata:
  name: stdout-output
  namespace: logging
spec:
  match: kube.*
  stdout: {}
